[project]
name = "masters-thesis"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "accelerate==1.5.2",
    "bitsandbytes==0.45.3",
    "datasets==3.4.1",
    "einops==0.8.1",
    "numpy==1.26.4",
    "pandas==2.2.3",
    "peft==0.15.0",
    "ray==2.40.0",
    "regex==2024.11.6",
    "safetensors==0.5.3",
    "scikit-learn==1.6.1",
    "scipy==1.15.2",
    "sentencepiece==0.2.0",
    "tokenizers==0.21.1",
    "torch==2.5.1",
    "torchao==0.9.0",
    "torchaudio==2.5.1",
    "torchvision==0.20.1",
    "tqdm==4.67.1",
    "unsloth-zoo<=2025.11.3",
    "wandb==0.19.8",
    "xformers==0.0.28.post3",
]
