[project]
name = "masters-thesis"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "trl",
    "wandb>=0.23.0",
]

[tool.uv.workspace]
members = [
    "src/external/trl",
    "src/external/transformers",
]

[tool.uv.sources]
trl = { workspace = true, editable = true }

[tool.uv.extra-build-dependencies]
natten = ["torch"]
