[project]
name = "masters-thesis"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "bitsandbytes>=0.48.2",
    "datasets>=4.4.1",
    "debugpy>=1.8.17",
    "peft>=0.18.0",
    "wandb>=0.23.0",
]
